# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_themamap.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ThemaMapWidget(object):
    def setupUi(self, ThemaMapWidget):
        ThemaMapWidget.setObjectName(_fromUtf8("ThemaMapWidget"))
        ThemaMapWidget.resize(450, 460)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ThemaMapWidget.sizePolicy().hasHeightForWidth())
        ThemaMapWidget.setSizePolicy(sizePolicy)
        ThemaMapWidget.setMinimumSize(QtCore.QSize(450, 415))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(ThemaMapWidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.uSymbolTabWidget = QtGui.QTabWidget(ThemaMapWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uSymbolTabWidget.sizePolicy().hasHeightForWidth())
        self.uSymbolTabWidget.setSizePolicy(sizePolicy)
        self.uSymbolTabWidget.setAutoFillBackground(False)
        self.uSymbolTabWidget.setObjectName(_fromUtf8("uSymbolTabWidget"))
        self.prop_symb = QtGui.QWidget()
        self.prop_symb.setObjectName(_fromUtf8("prop_symb"))
        self.gridLayout_6 = QtGui.QGridLayout(self.prop_symb)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.prop_symb)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 339))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 394, 387))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.uSymbolStyleLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uSymbolStyleLabel.setFont(font)
        self.uSymbolStyleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uSymbolStyleLabel.setObjectName(_fromUtf8("uSymbolStyleLabel"))
        self.gridLayout_7.addWidget(self.uSymbolStyleLabel, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.uPropSymbAttrLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uPropSymbAttrLabel.setFont(font)
        self.uPropSymbAttrLabel.setObjectName(_fromUtf8("uPropSymbAttrLabel"))
        self.horizontalLayout_7.addWidget(self.uPropSymbAttrLabel)
        self.uPropSymbAttrMenu = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.uPropSymbAttrMenu.setObjectName(_fromUtf8("uPropSymbAttrMenu"))
        self.horizontalLayout_7.addWidget(self.uPropSymbAttrMenu)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 3)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_7.addWidget(self.line, 1, 0, 1, 3)
        self.uSymbolSizeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uSymbolSizeLabel.setFont(font)
        self.uSymbolSizeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uSymbolSizeLabel.setObjectName(_fromUtf8("uSymbolSizeLabel"))
        self.gridLayout_7.addWidget(self.uSymbolSizeLabel, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.uCalibrationSizeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uCalibrationSizeLabel.setFont(font)
        self.uCalibrationSizeLabel.setObjectName(_fromUtf8("uCalibrationSizeLabel"))
        self.gridLayout_3.addWidget(self.uCalibrationSizeLabel, 0, 0, 1, 1)
        self.uCalibrationSize = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uCalibrationSize.setFont(font)
        self.uCalibrationSize.setObjectName(_fromUtf8("uCalibrationSize"))
        self.gridLayout_3.addWidget(self.uCalibrationSize, 0, 1, 1, 1)
        self.uCalibrationValueLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uCalibrationValueLabel.setFont(font)
        self.uCalibrationValueLabel.setObjectName(_fromUtf8("uCalibrationValueLabel"))
        self.gridLayout_3.addWidget(self.uCalibrationValueLabel, 1, 0, 1, 1)
        self.uCalibrationValue = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uCalibrationValue.setFont(font)
        self.uCalibrationValue.setObjectName(_fromUtf8("uCalibrationValue"))
        self.gridLayout_3.addWidget(self.uCalibrationValue, 1, 1, 1, 1)
        self.uBiasLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uBiasLabel.setFont(font)
        self.uBiasLabel.setObjectName(_fromUtf8("uBiasLabel"))
        self.gridLayout_3.addWidget(self.uBiasLabel, 2, 0, 1, 1)
        self.uBias = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uBias.setFont(font)
        self.uBias.setObjectName(_fromUtf8("uBias"))
        self.gridLayout_3.addWidget(self.uBias, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 2, 1, 1, 2)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_7.addWidget(self.line_2, 3, 0, 1, 3)
        self.uSymbolShapeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uSymbolShapeLabel.setFont(font)
        self.uSymbolShapeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uSymbolShapeLabel.setObjectName(_fromUtf8("uSymbolShapeLabel"))
        self.gridLayout_7.addWidget(self.uSymbolShapeLabel, 4, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.uSymbolShapeSquare = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolShapeSquare.setFont(font)
        self.uSymbolShapeSquare.setObjectName(_fromUtf8("uSymbolShapeSquare"))
        self.horizontalLayout_8.addWidget(self.uSymbolShapeSquare)
        self.uSymbolShapeCircle = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolShapeCircle.setFont(font)
        self.uSymbolShapeCircle.setObjectName(_fromUtf8("uSymbolShapeCircle"))
        self.horizontalLayout_8.addWidget(self.uSymbolShapeCircle)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.uSymbolFlannery = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolFlannery.setFont(font)
        self.uSymbolFlannery.setObjectName(_fromUtf8("uSymbolFlannery"))
        self.gridLayout_4.addWidget(self.uSymbolFlannery, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 4, 1, 1, 2)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_7.addWidget(self.line_3, 5, 0, 1, 3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.uSymbolStyleFillColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolStyleFillColorLabel.setFont(font)
        self.uSymbolStyleFillColorLabel.setObjectName(_fromUtf8("uSymbolStyleFillColorLabel"))
        self.gridLayout_5.addWidget(self.uSymbolStyleFillColorLabel, 0, 0, 1, 1)
        self.uSymbolStyleFillColor = QgsColorButtonV2(self.scrollAreaWidgetContents)
        self.uSymbolStyleFillColor.setObjectName(_fromUtf8("uSymbolStyleFillColor"))
        self.gridLayout_5.addWidget(self.uSymbolStyleFillColor, 0, 1, 1, 1)
        self.uSymbolStyleStrokeColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolStyleStrokeColorLabel.setFont(font)
        self.uSymbolStyleStrokeColorLabel.setObjectName(_fromUtf8("uSymbolStyleStrokeColorLabel"))
        self.gridLayout_5.addWidget(self.uSymbolStyleStrokeColorLabel, 1, 0, 1, 1)
        self.uSymbolStyleStrokeColor = QgsColorButtonV2(self.scrollAreaWidgetContents)
        self.uSymbolStyleStrokeColor.setObjectName(_fromUtf8("uSymbolStyleStrokeColor"))
        self.gridLayout_5.addWidget(self.uSymbolStyleStrokeColor, 1, 1, 1, 1)
        self.uSymbolStyleStrokeWidthLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uSymbolStyleStrokeWidthLabel.setFont(font)
        self.uSymbolStyleStrokeWidthLabel.setObjectName(_fromUtf8("uSymbolStyleStrokeWidthLabel"))
        self.gridLayout_5.addWidget(self.uSymbolStyleStrokeWidthLabel, 2, 0, 1, 1)
        self.uSymbolStyleStrokeWidth = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.uSymbolStyleStrokeWidth.setSingleStep(0.1)
        self.uSymbolStyleStrokeWidth.setProperty("value", 0.3)
        self.uSymbolStyleStrokeWidth.setObjectName(_fromUtf8("uSymbolStyleStrokeWidth"))
        self.gridLayout_5.addWidget(self.uSymbolStyleStrokeWidth, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 6, 1, 2, 2)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 8, 1, 1, 1)
        self.line.raise_()
        self.uSymbolStyleLabel.raise_()
        self.uSymbolShapeLabel.raise_()
        self.line_2.raise_()
        self.uSymbolSizeLabel.raise_()
        self.line_3.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.uSymbolTabWidget.addTab(self.prop_symb, _fromUtf8(""))
        self.fill_color = QtGui.QWidget()
        self.fill_color.setObjectName(_fromUtf8("fill_color"))
        self.gridLayout_8 = QtGui.QGridLayout(self.fill_color)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.scrollArea_2 = QtGui.QScrollArea(self.fill_color)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 384, 417))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uChoroplethAttrLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethAttrLabel.setFont(font)
        self.uChoroplethAttrLabel.setObjectName(_fromUtf8("uChoroplethAttrLabel"))
        self.horizontalLayout_3.addWidget(self.uChoroplethAttrLabel)
        self.uChoroplethAttr = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.uChoroplethAttr.setObjectName(_fromUtf8("uChoroplethAttr"))
        self.horizontalLayout_3.addWidget(self.uChoroplethAttr)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_9.addWidget(self.line_4, 1, 0, 1, 2)
        self.uChoroplethColorsLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uChoroplethColorsLabel.setFont(font)
        self.uChoroplethColorsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uChoroplethColorsLabel.setObjectName(_fromUtf8("uChoroplethColorsLabel"))
        self.gridLayout_9.addWidget(self.uChoroplethColorsLabel, 2, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uChoroplethNClassesLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethNClassesLabel.setFont(font)
        self.uChoroplethNClassesLabel.setObjectName(_fromUtf8("uChoroplethNClassesLabel"))
        self.gridLayout.addWidget(self.uChoroplethNClassesLabel, 2, 0, 1, 1)
        self.uChoroplethSchemeTypeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethSchemeTypeLabel.setFont(font)
        self.uChoroplethSchemeTypeLabel.setObjectName(_fromUtf8("uChoroplethSchemeTypeLabel"))
        self.gridLayout.addWidget(self.uChoroplethSchemeTypeLabel, 4, 0, 1, 1)
        self.uChoroplethSchemeType = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.uChoroplethSchemeType.setObjectName(_fromUtf8("uChoroplethSchemeType"))
        self.uChoroplethSchemeType.addItem(_fromUtf8(""))
        self.uChoroplethSchemeType.addItem(_fromUtf8(""))
        self.uChoroplethSchemeType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.uChoroplethSchemeType, 4, 1, 1, 1)
        self.uChoroplethSchemeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethSchemeLabel.setFont(font)
        self.uChoroplethSchemeLabel.setObjectName(_fromUtf8("uChoroplethSchemeLabel"))
        self.gridLayout.addWidget(self.uChoroplethSchemeLabel, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uChoroplethScheme = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.uChoroplethScheme.setObjectName(_fromUtf8("uChoroplethScheme"))
        self.horizontalLayout.addWidget(self.uChoroplethScheme)
        self.uChoroplethSchemeButton = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.uChoroplethSchemeButton.setObjectName(_fromUtf8("uChoroplethSchemeButton"))
        self.horizontalLayout.addWidget(self.uChoroplethSchemeButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.uChoroplethLimitsLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethLimitsLabel.setFont(font)
        self.uChoroplethLimitsLabel.setObjectName(_fromUtf8("uChoroplethLimitsLabel"))
        self.gridLayout.addWidget(self.uChoroplethLimitsLabel, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uChoroplethLimits = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethLimits.setFont(font)
        self.uChoroplethLimits.setObjectName(_fromUtf8("uChoroplethLimits"))
        self.horizontalLayout_2.addWidget(self.uChoroplethLimits)
        self.uChoroplethLimitsButton = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.uChoroplethLimitsButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.uChoroplethLimitsButton.setObjectName(_fromUtf8("uChoroplethLimitsButton"))
        self.horizontalLayout_2.addWidget(self.uChoroplethLimitsButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.uChoroplethCriticalValueLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethCriticalValueLabel.setFont(font)
        self.uChoroplethCriticalValueLabel.setObjectName(_fromUtf8("uChoroplethCriticalValueLabel"))
        self.gridLayout.addWidget(self.uChoroplethCriticalValueLabel, 7, 0, 1, 1)
        self.uChoroplethNoDataLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethNoDataLabel.setFont(font)
        self.uChoroplethNoDataLabel.setObjectName(_fromUtf8("uChoroplethNoDataLabel"))
        self.gridLayout.addWidget(self.uChoroplethNoDataLabel, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uChoroplethNClasses = QtGui.QSpinBox(self.scrollAreaWidgetContents_2)
        self.uChoroplethNClasses.setObjectName(_fromUtf8("uChoroplethNClasses"))
        self.horizontalLayout_4.addWidget(self.uChoroplethNClasses)
        spacerItem1 = QtGui.QSpacerItem(128, 33, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.uChoroplethCriticalValue = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethCriticalValue.setFont(font)
        self.uChoroplethCriticalValue.setObjectName(_fromUtf8("uChoroplethCriticalValue"))
        self.horizontalLayout_5.addWidget(self.uChoroplethCriticalValue)
        spacerItem2 = QtGui.QSpacerItem(78, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.uChoroplethNoData = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethNoData.setFont(font)
        self.uChoroplethNoData.setObjectName(_fromUtf8("uChoroplethNoData"))
        self.horizontalLayout_6.addWidget(self.uChoroplethNoData)
        spacerItem3 = QtGui.QSpacerItem(78, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_9.addWidget(self.line_5, 3, 0, 1, 2)
        self.uChoroplethPolygonStyleLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uChoroplethPolygonStyleLabel.setFont(font)
        self.uChoroplethPolygonStyleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uChoroplethPolygonStyleLabel.setObjectName(_fromUtf8("uChoroplethPolygonStyleLabel"))
        self.gridLayout_9.addWidget(self.uChoroplethPolygonStyleLabel, 4, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uChoroplethFillColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethFillColorLabel.setFont(font)
        self.uChoroplethFillColorLabel.setObjectName(_fromUtf8("uChoroplethFillColorLabel"))
        self.gridLayout_2.addWidget(self.uChoroplethFillColorLabel, 0, 0, 1, 1)
        self.uChoroplethFillColor = QgsColorButtonV2(self.scrollAreaWidgetContents_2)
        self.uChoroplethFillColor.setObjectName(_fromUtf8("uChoroplethFillColor"))
        self.gridLayout_2.addWidget(self.uChoroplethFillColor, 0, 1, 1, 1)
        self.uChoroplethStrokeColorLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethStrokeColorLabel.setFont(font)
        self.uChoroplethStrokeColorLabel.setObjectName(_fromUtf8("uChoroplethStrokeColorLabel"))
        self.gridLayout_2.addWidget(self.uChoroplethStrokeColorLabel, 1, 0, 1, 1)
        self.uChoroplethStrokeColor = QgsColorButtonV2(self.scrollAreaWidgetContents_2)
        self.uChoroplethStrokeColor.setObjectName(_fromUtf8("uChoroplethStrokeColor"))
        self.gridLayout_2.addWidget(self.uChoroplethStrokeColor, 1, 1, 1, 1)
        self.uChoroplethStrokeWidthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uChoroplethStrokeWidthLabel.setFont(font)
        self.uChoroplethStrokeWidthLabel.setObjectName(_fromUtf8("uChoroplethStrokeWidthLabel"))
        self.gridLayout_2.addWidget(self.uChoroplethStrokeWidthLabel, 2, 0, 1, 1)
        self.uChoroplethStrokeWidth = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.uChoroplethStrokeWidth.setSingleStep(0.1)
        self.uChoroplethStrokeWidth.setProperty("value", 0.3)
        self.uChoroplethStrokeWidth.setObjectName(_fromUtf8("uChoroplethStrokeWidth"))
        self.gridLayout_2.addWidget(self.uChoroplethStrokeWidth, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 5, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.uSymbolTabWidget.addTab(self.fill_color, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.uSymbolTabWidget)

        self.retranslateUi(ThemaMapWidget)
        self.uSymbolTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ThemaMapWidget)

    def retranslateUi(self, ThemaMapWidget):
        ThemaMapWidget.setWindowTitle(_translate("ThemaMapWidget", "Form", None))
        self.uSymbolStyleLabel.setText(_translate("ThemaMapWidget", "Symbol style", None))
        self.uPropSymbAttrLabel.setText(_translate("ThemaMapWidget", "Attribute", None))
        self.uSymbolSizeLabel.setText(_translate("ThemaMapWidget", "Symbol size", None))
        self.uCalibrationSizeLabel.setText(_translate("ThemaMapWidget", "Calibration size", None))
        self.uCalibrationValueLabel.setText(_translate("ThemaMapWidget", "Calibration value", None))
        self.uBiasLabel.setText(_translate("ThemaMapWidget", "Bias", None))
        self.uSymbolShapeLabel.setText(_translate("ThemaMapWidget", "Symbol shape", None))
        self.uSymbolShapeSquare.setText(_translate("ThemaMapWidget", "Square", None))
        self.uSymbolShapeCircle.setText(_translate("ThemaMapWidget", "Circle", None))
        self.uSymbolFlannery.setText(_translate("ThemaMapWidget", "Flannery appearance compensation", None))
        self.uSymbolStyleFillColorLabel.setText(_translate("ThemaMapWidget", "Fill color", None))
        self.uSymbolStyleFillColor.setToolTip(_translate("ThemaMapWidget", "Change the arrow colour", None))
        self.uSymbolStyleFillColor.setText(_translate("ThemaMapWidget", "change", None))
        self.uSymbolStyleStrokeColorLabel.setText(_translate("ThemaMapWidget", "Stroke color", None))
        self.uSymbolStyleStrokeColor.setToolTip(_translate("ThemaMapWidget", "Change the arrow colour", None))
        self.uSymbolStyleStrokeColor.setText(_translate("ThemaMapWidget", "change", None))
        self.uSymbolStyleStrokeWidthLabel.setText(_translate("ThemaMapWidget", "Stroke width", None))
        self.uSymbolTabWidget.setTabText(self.uSymbolTabWidget.indexOf(self.prop_symb), _translate("ThemaMapWidget", "Proportional Symbol", None))
        self.uChoroplethAttrLabel.setText(_translate("ThemaMapWidget", "Attribute", None))
        self.uChoroplethColorsLabel.setText(_translate("ThemaMapWidget", "Colors", None))
        self.uChoroplethNClassesLabel.setText(_translate("ThemaMapWidget", "Number of classes", None))
        self.uChoroplethSchemeTypeLabel.setText(_translate("ThemaMapWidget", "Color scheme type", None))
        self.uChoroplethSchemeType.setItemText(0, _translate("ThemaMapWidget", "Sequential", None))
        self.uChoroplethSchemeType.setItemText(1, _translate("ThemaMapWidget", "Divergent", None))
        self.uChoroplethSchemeType.setItemText(2, _translate("ThemaMapWidget", "Qualitative", None))
        self.uChoroplethSchemeLabel.setText(_translate("ThemaMapWidget", "Color scheme", None))
        self.uChoroplethSchemeButton.setText(_translate("ThemaMapWidget", "...", None))
        self.uChoroplethLimitsLabel.setText(_translate("ThemaMapWidget", "Class limits", None))
        self.uChoroplethLimitsButton.setText(_translate("ThemaMapWidget", "...", None))
        self.uChoroplethCriticalValueLabel.setText(_translate("ThemaMapWidget", "Critical value", None))
        self.uChoroplethNoDataLabel.setText(_translate("ThemaMapWidget", "No data value", None))
        self.uChoroplethPolygonStyleLabel.setText(_translate("ThemaMapWidget", "Polygon style", None))
        self.uChoroplethFillColorLabel.setText(_translate("ThemaMapWidget", "Fill color", None))
        self.uChoroplethFillColor.setToolTip(_translate("ThemaMapWidget", "Change the arrow colour", None))
        self.uChoroplethFillColor.setText(_translate("ThemaMapWidget", "change", None))
        self.uChoroplethStrokeColorLabel.setText(_translate("ThemaMapWidget", "Stroke color", None))
        self.uChoroplethStrokeColor.setToolTip(_translate("ThemaMapWidget", "Change the arrow colour", None))
        self.uChoroplethStrokeColor.setText(_translate("ThemaMapWidget", "change", None))
        self.uChoroplethStrokeWidthLabel.setText(_translate("ThemaMapWidget", "Stroke width", None))
        self.uSymbolTabWidget.setTabText(self.uSymbolTabWidget.indexOf(self.fill_color), _translate("ThemaMapWidget", "Fill Color", None))

from qgis.gui import QgsColorButtonV2
